name: CI Build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'    
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  
permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry
  
jobs:

# Build MAUI Windows
  build-windows:
    runs-on: windows-latest
    name: Windows Build
    steps:
    
    - uses: actions/checkout@v3
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Install MAUI workload
      run: dotnet workload install maui
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build MAUI windows
      run: dotnet publish -c Release -f net8.0-windows10.0.19041.0 -p:PublishReadyToRun=true

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: skarnes20-ado-manager
        path: src\Manager\Manager.csproj::TargetFramework=net8.0-windows10.0.19041.0/win10-x64/AppPackages/Manager*/Manager*.msix      
